<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Word;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * @param array|null $excludedIds
     * @param string|null $lang
     * @param int $numberOfWords
     *
     * @return Word|Word[]|null
     */
    public function findRandomWord(array $excludedIds = null, string $lang = null, int $numberOfWords = 1) {

        $qb = $this->createQueryBuilder('w');

        if ($excludedIds !== null && count($excludedIds)) {
            $qb->where('w.id NOT IN (:excludedIds)')->setParameter('excludedIds', $excludedIds);
        }

        if ($lang) {
            $qb->andWhere('w.lang = :lang')->setParameter('lang', $lang);
        }

        $qb->addSelect('RANDOM() as HIDDEN rand')->orderBy('rand');

        if ($numberOfWords === 1) {
            return $qb->getQuery()->setMaxResults(1)->getSingleResult();
        } else {
            return $qb->setMaxResults($numberOfWords)->getQuery()->getResult();
        }
    }
}
